version: '3.8'

volumes:
  pgadmin-data:
  postgres_data:
  data:  # Ajout du volume pour le dossier data

services:
  airflow-db:
    image: postgres:13
    container_name: airflow-db
    restart: always
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:latest
    container_name: airflow-redis
    restart: always
    ports:
      - "6379:6379"

  airflow-init:
    image: apache/airflow:2.6.3
    container_name: airflow-init
    depends_on:
      - airflow-db
      - redis
    env_file:
      - .env
    volumes:
      - ./scripts/entrypoint.sh:/entrypoint.sh
      - ./logs:/opt/airflow/logs
      - ./data:/usr/local/airflow/data  # Montage du dossier data
    entrypoint: ["/bin/bash", "/entrypoint.sh"]

  airflow-webserver:
    image: apache/airflow:2.6.3
    container_name: airflow-webserver
    restart: always
    depends_on:
      - airflow-init
      - airflow-scheduler
      - redis
    env_file:
      - .env
    volumes:
      - ./dags:/opt/airflow/dags
      - ./logs:/opt/airflow/logs
      - ./plugins:/opt/airflow/plugins
      - ./data:/usr/local/airflow/data  # Montage du dossier data
    ports:
      - "8080:8080"
    command: webserver

  airflow-scheduler:
    image: apache/airflow:2.6.3
    container_name: airflow-scheduler
    restart: always
    depends_on:
      - airflow-init
      - redis
    env_file:
      - .env
    volumes:
      - ./dags:/opt/airflow/dags
      - ./logs:/opt/airflow/logs
      - ./plugins:/opt/airflow/plugins
      - ./data:/usr/local/airflow/data  # Montage du dossier data
    command: scheduler


# version: '3.8'

# volumes:
#   pgadmin-data:
#   postgres_data:

# services:
#   airflow-db:
#     image: postgres:13
#     container_name: airflow-db
#     restart: always
#     environment:
#       POSTGRES_USER: airflow
#       POSTGRES_PASSWORD: airflow
#       POSTGRES_DB: airflow
#     ports:
#       - "5432:5432"
#     volumes:
#       - postgres_data:/var/lib/postgresql/data

#   redis:
#     image: redis:latest
#     container_name: airflow-redis
#     restart: always
#     ports:
#       - "6379:6379"

#   airflow-init:
#     image: apache/airflow:2.6.3
#     container_name: airflow-init
#     depends_on:
#       - airflow-db
#       - redis
#     env_file:
#       - .env
#     volumes:
#       - ./scripts/entrypoint.sh:/entrypoint.sh
#       - ./logs:/opt/airflow/logs
#     entrypoint: ["/bin/bash", "/entrypoint.sh"]

#   airflow-webserver:
#     image: apache/airflow:2.6.3
#     container_name: airflow-webserver
#     restart: always
#     depends_on:
#       - airflow-init
#       - airflow-scheduler
#       - redis
#     env_file:
#       - .env
#     volumes:
#       - ./dags:/opt/airflow/dags
#       - ./logs:/opt/airflow/logs
#       - ./plugins:/opt/airflow/plugins
#     ports:
#       - "8080:8080"
#     command: webserver

#   airflow-scheduler:
#     image: apache/airflow:2.6.3
#     container_name: airflow-scheduler
#     restart: always
#     depends_on:
#       - airflow-init
#       - redis
#     env_file:
#       - .env
#     volumes:
#       - ./dags:/opt/airflow/dags
#       - ./logs:/opt/airflow/logs
#       - ./plugins:/opt/airflow/plugins
#     command: scheduler


  # docs:
  #   build:
  #     context: .
  #     dockerfile: ./docs/Dockerfile
  #   image: pipeline_etl_docs
  #   container_name: pipeline_etl_docs
  #   volumes:
  #     - .:/app/:z
  #   restart: always
  #   ports:
  #     - "9021:9000"
  #   env_file:
  #     - ./.env
  #   command: mkdocs serve -a 0.0.0.0:9000
